---
eda_credentials_all:
  - name: controller-fulfillment-credentials
    description: user that allows EDA to trigger jobs on the controller
    organization: fulfillment
    credential_type: 'Red Hat Ansible Automation Platform'
    inputs: 
      username: controller-fulfillment-service-user
      password: "qwerty1234"
      host: "{{ aap_hostname }}/api/controller/"
  - name: controller-fulfillment-credential
    organization: fulfillment
    credential_type: 'Red Hat Ansible Automation Platform'
    state: absent
...
