---
aap_hostname: "https://fulfillment-fulfillment-aap.apps-crc.testing"
aap_validate_certs: false
controller_configuration_users_secure_logging: false
eda_configuration_credentials_secure_logging: false
env: crc

# controller_hosts: "{{ controller_hosts_all }}"
#aap_applications: "{{ aap_applications_all + aap_applications_dev }}"
#aap_teams: "{{ aap_teams_all + aap_teams_dev }}"
#controller_credential_input_sources: "{{ controller_credential_input_sources_all + controller_credential_input_sources_dev }}"
#controller_credential_types: "{{ controller_credential_types_all + controller_credential_types_dev }}"
#controller_credentials: "{{ controller_credentials_all + controller_credentials_dev }}"
#controller_execution_environments: "{{ controller_execution_environments_all + controller_execution_environments_dev }}"
#controller_groups: "{{ controller_groups_all + controller_groups_dev }}"
#controller_instance_groups: "{{ controller_instance_groups_all + controller_instance_groups_dev }}"
#controller_labels: "{{ controller_labels_all + controller_labels_dev }}"
#controller_notifications: "{{ controller_notifications_all + controller_notifications_dev }}"
#controller_roles: "{{ controller_roles_all + controller_roles_dev }}"
#controller_schedules: "{{ controller_schedules_all + controller_schedules_dev }}"
#controller_settings: "{{ controller_settings_all | combine(controller_settings_dev, list_merge='append', recursive=true) }}"
#controller_workflows: "{{ controller_workflows_all + controller_workflows_dev }}"
#scm_branch: "" # when you want it to be default branch just set to ""
aap_organizations: "{{ aap_organizations_all }}"
aap_user_accounts: "{{ aap_user_accounts_all }}" # + aap_user_accounts_dev }}"
controller_inventories: "{{ controller_inventories_all }}"
controller_inventory_sources: "{{ controller_inventory_sources_all }}"
controller_projects: "{{ controller_projects_all }}"
controller_templates: "{{ controller_templates_all }}"
controller_roles: "{{ controller_roles_all }}"
eda_projects: "{{ eda_projects_all }}"
eda_decision_environments: "{{ eda_decision_environments_all }}"
eda_rulebook_activations: "{{ eda_rulebook_activations_all }}"
eda_credentials: "{{ eda_credentials_all }}"
...
