- name: Setup subscription
  hosts: "{{ env | default('dev') }}" # noqa: syntax-check
  vars_files:
    - "../vaults/{{ env }}.yml"
  connection: local
  tasks:
    - name: Get subscriptions with a filter
      awx.awx.subscriptions:
        username: "{{ rh_username }}"
        password: "{{ rh_password }}"
        filters:
          product_name: Red Hat Ansible Automation Platform
          support_level: Self-Support
        controller_host: "{{ controller_hostname }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: false
      register: subscription

    - name: Attach to a pool
      awx.awx.license:
        pool_id: "{{ subscription.subscriptions[0].pool_id }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        controller_host: "{{ controller_hostname }}"
        validate_certs: false
